#!/usr/bin/env python3
"""
Split each PKL motion under assets/motions/g1_pkl into 3 temporal chunks.

Output naming:
    <original_stem>_0.pkl  # first 1/3
    <original_stem>_1.pkl  # middle 1/3
    <original_stem>_2.pkl  # last 1/3
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import joblib
import numpy as np


def split_ranges(num_frames: int) -> list[tuple[int, int]]:
    """Return 3 contiguous ranges covering [0, num_frames)."""
    b1 = num_frames // 3
    b2 = (2 * num_frames) // 3
    return [(0, b1), (b1, b2), (b2, num_frames)]


def _slice_time_aligned(value: Any, total_frames: int, start: int, end: int) -> Any:
    """Recursively slice values whose leading dimension matches total_frames."""
    if isinstance(value, np.ndarray):
        if value.ndim >= 1 and value.shape[0] == total_frames:
            return value[start:end].copy()
        return value.copy()

    if isinstance(value, dict):
        return {k: _slice_time_aligned(v, total_frames, start, end) for k, v in value.items()}

    if isinstance(value, list):
        return [_slice_time_aligned(v, total_frames, start, end) for v in value]

    if isinstance(value, tuple):
        return tuple(_slice_time_aligned(v, total_frames, start, end) for v in value)

    return value


def slice_motion(motion: dict[str, Any], start: int, end: int) -> dict[str, Any]:
    """Slice time-dependent fields by frame range [start:end], including nested IK data."""
    total_frames = int(np.asarray(motion["dof_pos"]).shape[0])
    return {
        key: _slice_time_aligned(value, total_frames, start, end)
        for key, value in motion.items()
    }


def split_one_file(
    pkl_path: Path,
    input_root: Path,
    output_root: Path,
    overwrite: bool,
) -> int:
    """Split one pkl into 3 files. Returns number of files written."""
    motion = joblib.load(pkl_path)
    if "dof_pos" not in motion:
        print(f"[WARN] Skip (missing dof_pos): {pkl_path}")
        return 0

    num_frames = int(np.asarray(motion["dof_pos"]).shape[0])
    if num_frames < 3:
        print(f"[WARN] Skip (frames < 3): {pkl_path} ({num_frames} frames)")
        return 0

    ranges = split_ranges(num_frames)
    written = 0
    rel_parent = pkl_path.relative_to(input_root).parent
    out_dir = output_root / rel_parent
    out_dir.mkdir(parents=True, exist_ok=True)

    for idx, (start, end) in enumerate(ranges):
        out_path = out_dir / f"{pkl_path.stem}_{idx}.pkl"
        if out_path.exists() and not overwrite:
            print(f"[SKIP] Exists: {out_path}")
            continue

        part = slice_motion(motion, start, end)
        joblib.dump(part, out_path)
        written += 1

    return written


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Split all PKL motions into 3 temporal chunks."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("assets/motions/g1_pkl"),
        help="Input root directory containing pkl files.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("assets/motions/g1_pkl_split3"),
        help="Output root directory for split files.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing *_0/_1/_2 files if they already exist.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_dir: Path = args.input_dir
    output_dir: Path = args.output_dir
    overwrite: bool = args.overwrite

    if not input_dir.is_dir():
        raise FileNotFoundError(f"Input directory does not exist: {input_dir}")
    output_dir.mkdir(parents=True, exist_ok=True)

    pkl_files = sorted(input_dir.rglob("*.pkl"))
    # Avoid repeatedly splitting files generated by this script.
    pkl_files = [p for p in pkl_files if not p.stem.endswith(("_0", "_1", "_2"))]

    total = len(pkl_files)
    written = 0
    for idx, pkl_path in enumerate(pkl_files, start=1):
        written += split_one_file(
            pkl_path,
            input_root=input_dir,
            output_root=output_dir,
            overwrite=overwrite,
        )
        if idx % 200 == 0 or idx == total:
            print(f"[INFO] Progress: {idx}/{total}")

    print(f"[DONE] Source motions: {total}")
    print(f"[DONE] Output files written: {written}")
    print(f"[DONE] Output root: {output_dir.resolve()}")


if __name__ == "__main__":
    main()
